### ISSUE TITLE
[Tracker] Roadmap

### ISSUE THREAD

**Issue by fire** [godot-extended-libraries/godot-sqlite#1]
Suggestions for things to do?

@TGRCdev

**Comment by TGRCdev** [comment]
I'm currently building the module to make sure it works. For now, I'm gonna focus on making sure the module matches the functionality of the GDNative library.

Here's my first thoughts for a roadmap:
- [x] Merge BLOB support from gdsqlite-native
- [x] Add documentation for the methods
- [ ] Write a CI config to make sure major platforms are still buildable
    - [ ] BONUS: Build a first release of editor binaries and export templates using CI?

Later on we can look at any missing functionality from SQLite and determine the best way to proceed.

**Comment by fire** [comment]
Want to write up a issue for each? 

https://github.com/godotengine/godot-proposals/blob/master/.github/ISSUE_TEMPLATE/feature---enhacement-proposal.md

**Comment by TGRCdev** [comment]
That'd be a good idea. Makes assigning a lot easier.

**Comment by TGRCdev** [comment]
I'll cross them off as I get time, but if you want to take initiative on any of them, you can assign yourself.

**Comment by fire** [comment]
Closing this since only CICD is left.
